CREATE TABLE observations (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    individual_local_identifier TEXT REFERENCES individuals(individual_local_identifier) ON DELETE CASCADE NOT NULL,
    -- Get help - raw data are unix timestamps*1000
    time_stamp NUMERIC NOT NULL,
    -- Change this to use point datatype - PostGIS?
    location_long DOUBLE PRECISION NOT NULL,
    location_lat DOUBLE PRECISION NOT NULL,
    heading NUMERIC,
    ground_speed NUMERIC
);