CREATE TABLE observations (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    individual_id TEXT REFERENCES individuals(individual_local_identifier) ON DELETE CASCADE NOT NULL,
    time_stamp TIMESTAMP NOT NULL,
    location_long DOUBLE PRECISION NOT NULL,
    location_lat DOUBLE PRECISION NOT NULL,
    heading NUMERIC,
    ground_speed NUMERIC
);

CREATE INDEX time_index ON observations(time_stamp);

CREATE INDEX individual_index ON observations(individual_id);